### ISSUE TITLE
Change controls

### ISSUE THREAD

**Issue by CrimsonFork** [meoblast001/thugaim#5]
It is very difficult to control the spaceship, for now I'm just hold the phone in 90° and touch the screen until no enemy is left ;-)

But seriously, there's actually no way you can focus on anything that's moving if you have to rethink the controls every 0.5 seconds.

My suggestion is to invert the envrioment: instead of the spaceship moving in the space, the world should be moving around the spaceship, this would make the control much easier.

**Comment by meoblast001** [comment]
This is something I considered during development. Because I'm not sure how current players would react to this change, I could try to make some kind of "lock rotation to player" mode, that can be toggled on and off at start.

**Comment by CrimsonFork** [comment]
Maybe an other name? I wouldn't know what to think about this option if I didn't read this issue.
